apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-pod

spec:
  template:
     metadata:
       name: app-pod
       labels:
        app: app-pod
     spec:
       containers:
         - name: app-pod
           env:
             - name: DB_SERVER
               value: db-service
             - name: DB_NAME
               valueFrom: 
                secretKeyRef:
                 name: mysql-pass
                 key: dbname
             - name: DB_USERNAME
               valueFrom: 
                 secretKeyRef:
                  name: mysql-pass
                  key: username
             - name: DB_PASSWORD
               valueFrom:
                 secretKeyRef:
                  name: mysql-pass
                  key: password
           image: pawanitzone/myapp:9
           ports:
             - containerPort: 80

  replicas: 1
  selector:
    matchLabels:
      app: app-pod
