apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-deployment
  labels:
    app: db-pod

spec:
  template:
     metadata:
       name: db-pod
       labels:
         app: db-pod
     spec:
       
       containers:
         - name: db-pod
           image: pawanitzone/mydb:59
           env:
             - name: MYSQL_ALLOW_EMPTY_PASSWORD
               value: "1"
           #env:
           #  - name: MYSQL_ROOT_PASSWORD
           #    valueFrom:
           #     secretKeyRef:
           #      name: mysql-pass
           #      key: password

           volumeMounts:
           - mountPath: /var/lib/mysql
             name: db-volume
             subPath: mysql
           - name: conf
             mountPath: /etc/mysql/conf.d
           ports:
             - containerPort: 3306
             
           livenessProbe:
            exec:
             command: ["mysqladmin", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
     
       volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-pvc-claim
        - name: conf
          emptyDir: {}
         
  replicas: 2
  serviceName: db-service
  selector:
    matchLabels:
      app: db-pod
